development:
  adapter: postgresql
  encoding: utf8
  database: dfp_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: dfp_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: dfp_production
  pool: 5
  username:
  password:
