# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ee6366dfec6f40119b33498b5aad8932570c5b49365191493d7606b006d0cfb0fce3b15d7322384f26ec2e7a2d554df8c22ae33b3065cebd99e9d8f9700a911

test:
  secret_key_base: 9c01805d4ececa6939bff09e148100b95c4091fa36224d264d815c451b250e69b092f960ba7c32ee483c3377189af85c3e31890d76d4bd3d0828bc5e874b658c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
